# Generated by Django 4.0.4 on 2022-05-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.CharField(max_length=100, verbose_name='예약끝나는시간'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.CharField(max_length=100, verbose_name='예약시작시간'),
        ),
    ]
